Repository autowarefoundation/AWSIM-Labs, pull requests merged in 2024-08, with the labels that each got.

#128 fix: graphic settings camera list initialization
  Assets/AWSIM/Scripts/UI/BirdEyeView.cs
  Assets/AWSIM/Scripts/UI/GraphicsSettings.cs
Labels: type:bug

#96 feat: enable multi scene setup
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Scenes/Composition/AWSIMSimulation.unity
  Assets/AWSIM/Scenes/Composition/LoaderScene.unity
  Assets/AWSIM/Scenes/Environments/Shinjuku.unity
  Assets/AWSIM/Scenes/Environments/ShinjukuNight.unity
  Assets/AWSIM/Scripts/Loader/Loader.cs
  Assets/AWSIM/Scripts/Loader/SimConfiguration.cs
  Assets/AWSIM/Scripts/UI/BirdEyeView.cs
  Assets/AWSIM/Scripts/UI/EgoVehiclePositionManager.cs
  Assets/AWSIM/Scripts/UI/GraphicsSettings.cs
  Assets/AWSIM/Scripts/UI/Toggle/UIKeyboardControlToggle.cs
  Assets/AWSIM/Scripts/UI/Toggle/UIMainCameraToggle.cs
  Assets/AWSIM/Scripts/UI/Toggle/UITrafficControlPlayToggle.cs
  Assets/AWSIM/Scripts/UI/Toggle/UITrafficControlVisibilityToggle.cs
  Assets/AWSIM/Scripts/UI/TrafficControlManager.cs
  Assets/AWSIM/Scripts/UI/UICameraOutputCanvas.cs
  Assets/AWSIM/Scripts/UI/UICameraOutputCanvas.cs.meta
  Assets/AWSIM/Scripts/UI/UISensorInteractionPanel.cs
  Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
  Assets/StreamingAssets.meta
  Assets/StreamingAssets/config.json
  Assets/StreamingAssets/config.json.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: type:new-feature

#130 feat: keep session settings
  Assets/AWSIM/Scripts/UI/GraphicsSettings.cs
  Assets/AWSIM/Scripts/UI/Toggle/UIMainCameraToggle.cs
Labels: type:new-feature

#132 feat: interactive mode for rviz npcs
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/NPCs/RvizNPCSpawner/RVIZNPCSpawner.cs
  ProjectSettings/TagManager.asset
Labels: type:new-feature

#136 docs: add parking area page
  Assets/AWSIM/Scenes/Parking Area.unity
  Assets/AWSIM/Scenes/Parking Area.unity.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  docs/GettingStarted/ParkingArea/1.png
  docs/GettingStarted/ParkingArea/2.png
  docs/GettingStarted/ParkingArea/3.png
  docs/GettingStarted/ParkingArea/4.png
  docs/GettingStarted/ParkingArea/angeled_p.png
  docs/GettingStarted/ParkingArea/index.md
  docs/GettingStarted/ParkingArea/l_p.png
  docs/GettingStarted/ParkingArea/paralel_p.png
  mkdocs.yml
Labels: type:documentation, tag:deploy-docs
