Repository autowarefoundation/AWSIM-Labs, pull requests merged in 2024-05, with the labels that each got.

#67 feat: add slider for adjusting traffic density
  Assets/AWSIM/Prefabs/Environments/Nishishinjuku/Nishishinjuku RandomTraffic.prefab
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scenes/Samples/TrafficManagerSample/SpawnerTest.cs
  Assets/AWSIM/Scripts/RandomTraffic/RandomTrafficSimulator.cs
  Assets/AWSIM/Scripts/RandomTraffic/TrafficManager.cs
  Assets/AWSIM/Scripts/UI/Toggle/UITrafficControlPlayToggle.cs
  Assets/AWSIM/Scripts/UI/Toggle/UITrafficControlVisibilityToggle.cs
  Assets/AWSIM/Scripts/UI/TrafficControlManager.cs
  Assets/AWSIM/Scripts/UI/UIBridge.cs
  Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
  Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs.meta
  Assets/AWSIM/Textures/UI Icons/round_emoji_transportation_white_24dp.png
  Assets/AWSIM/Textures/UI Icons/round_emoji_transportation_white_24dp.png.meta
Labels: enhancement

#69 feat: add BEV orthographic camera
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/UI/BirdEyeView.cs
  Assets/AWSIM/Scripts/UI/BirdEyeView.cs.meta
  ProjectSettings/TagManager.asset
  docs/ProjectGuide/HotkeyList/index.md
Labels: enhancement, tag:deploy-docs

#72 feat: dynamic sensor placement
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/Editor/DynamicSensorPlacement.meta
  Assets/AWSIM/Scripts/Editor/DynamicSensorPlacement/DynamicSensorPlacement.cs
  Assets/AWSIM/Scripts/Editor/DynamicSensorPlacement/DynamicSensorPlacement.cs.meta
  docs/Components/Vehicle/DynamicSensorPlacement/image-1.png
  docs/Components/Vehicle/DynamicSensorPlacement/image-2.png
  docs/Components/Vehicle/DynamicSensorPlacement/image-3.png
  docs/Components/Vehicle/DynamicSensorPlacement/image.png
  docs/Components/Vehicle/DynamicSensorPlacement/index.md
  docs/Components/Vehicle/DynamicSensorPlacement/menu.gif
  mkdocs.yml
Labels: documentation, enhancement, tag:deploy-docs

#71 feat: graphics settings
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Resources.meta
  Assets/AWSIM/Resources/URP Presets.meta
  Assets/AWSIM/Resources/URP Presets/ForwardRenderer.asset
  Assets/AWSIM/Resources/URP Presets/ForwardRenderer.asset.meta
  Assets/AWSIM/Resources/URP Presets/LightingSettings.lighting
  Assets/AWSIM/Resources/URP Presets/LightingSettings.lighting.meta
  Assets/AWSIM/Resources/URP Presets/QualityPresets.meta
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-Custom.asset
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-Custom.asset.meta
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-HighQuality.asset
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-HighQuality.asset.meta
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-LowQuality.asset
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-LowQuality.asset.meta
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-MediumQuality.asset
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-MediumQuality.asset.meta
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-Ultra.asset
  Assets/AWSIM/Resources/URP Presets/QualityPresets/UniversalRP-Ultra.asset.meta
  Assets/AWSIM/Resources/URP Presets/Skybox_Mat.mat
  Assets/AWSIM/Resources/URP Presets/Skybox_Mat.mat.meta
  Assets/AWSIM/Resources/URP Presets/VolumeProfiles.meta
  Assets/AWSIM/Resources/URP Presets/VolumeProfiles/CameraSensorProfile.asset
  Assets/AWSIM/Resources/URP Presets/VolumeProfiles/CameraSensorProfile.asset.meta
  Assets/AWSIM/Resources/URP Presets/VolumeProfiles/MainCameraProfile.asset
  Assets/AWSIM/Resources/URP Presets/VolumeProfiles/MainCameraProfile.asset.meta
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/UI/BirdEyeView.cs
  Assets/AWSIM/Scripts/UI/GraphicsSettings.cs
  Assets/AWSIM/Scripts/UI/GraphicsSettings.cs.meta
  Assets/AWSIM/Scripts/UI/Toggle/UITrafficControlVisibilityToggle.cs
  Assets/AWSIM/Scripts/UI/UISideBarHandler.cs
  Assets/UniversalRenderPipelineGlobalSettings.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
Labels: enhancement

#78 fix: null reference errors
  Assets/AWSIM/Scripts/Editor/RandomTraffic/Environments/TrafficLaneEditor.cs
Labels: bug

#81 fix: wrong localization in autoware
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/Editor/DynamicSensorPlacement/DynamicSensorPlacement.cs
Labels: bug

#83 fix: remove ui rounded corners package
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/UI/UIFunctions.cs
  Assets/Unity-UI-Rounded-Corners.meta
  Assets/Unity-UI-Rounded-Corners/LICENSE
  Assets/Unity-UI-Rounded-Corners/LICENSE.meta
  Assets/Unity-UI-Rounded-Corners/README.md
  Assets/Unity-UI-Rounded-Corners/README.md.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/DestroyHelper.cs
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/DestroyHelper.cs.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Editor.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Editor/ImageWithIndependentRoundedCornersInspector.cs
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Editor/ImageWithIndependentRoundedCornersInspector.cs.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Editor/ImageWithRoundedCornersInspector.cs
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Editor/ImageWithRoundedCornersInspector.cs.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/ImageWithIndependentRoundedCorners.cs
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/ImageWithIndependentRoundedCorners.cs.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/ImageWithRoundedCorners.cs
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/ImageWithRoundedCorners.cs.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/IndependentRoundedCorners.shader
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/IndependentRoundedCorners.shader.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Nobi.UiRoundedCorners.asmdef
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/Nobi.UiRoundedCorners.asmdef.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/RoundedCorners.shader
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/RoundedCorners.shader.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/SDFUtils.cginc
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/SDFUtils.cginc.meta
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/ShaderSetup.cginc
  Assets/Unity-UI-Rounded-Corners/UiRoundedCorners/ShaderSetup.cginc.meta
  Assets/Unity-UI-Rounded-Corners/package.json
  Assets/Unity-UI-Rounded-Corners/package.json.meta
Labels: bug
