Repository autowarefoundation/AWSIM-Labs, pull requests merged in 2024-09, with the labels that each got.

#116 feat: VPP CE Integration
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Scenes/Composition/AWSIMSimulation.unity
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/UI/Toggle/UIKeyboardControlToggle.cs
  Assets/AWSIM/Scripts/UI/UICard.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Enums.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Enums/VPPControlMode.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Enums/VPPControlMode.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Enums/VPPSignal.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Enums/VPPSignal.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/IVehicleControlModes.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/IVehicleControlModes/ControlMode.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/IVehicleControlModes/ControlMode.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/IVehicleControlModes/IVehicleControlMode.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/IVehicleControlModes/IVehicleControlMode.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Ros2ToVPPInput.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Ros2ToVPPInput.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Ros2ToVPPUtilities.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/Ros2ToVPPUtilities.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/VPPToRos2Publisher.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/VPPToRos2Publisher.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/VPPVehicleSignalHandler.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/VPPVehicleSignalHandler.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VehicleVisualEffect.cs
  Assets/Vehicle Physics Pro.meta
  Assets/Vehicle Physics Pro/.gitignore
  Assets/Vehicle Physics Pro/Editor/csc.rsp
  Assets/Vehicle Physics Pro/Editor/csc.rsp.meta
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
  docs/Components/Vehicle/EgoVehicle/index.md
  docs/Components/Vehicle/VPPIntegration/index.md
  docs/DeveloperGuide/EditorSetup/VPPCommunityEdition/index.md
  docs/GettingStarted/QuickStartDemo/index.md
  docs/GettingStarted/SetupUnityProject/index.md
  mkdocs.yml
Labels: type:new-feature, tag:deploy-docs

#143 fix: traffic manager reference
  Assets/AWSIM/Scripts/UI/TrafficControlManager.cs
  Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
Labels: type:bug

#142 feat: add ss2 scene to launch setup
  Assets/AWSIM/Resources/SceneMetadata.meta
  Assets/AWSIM/Resources/SceneMetadata/SceneMetadataDatabase.asset
  Assets/AWSIM/Resources/SceneMetadata/SceneMetadataDatabase.asset.meta
  Assets/AWSIM/Scenes/Composition/LoaderScene.unity
  Assets/AWSIM/Scenes/Main/AutowareSimulationScenarioSimulator.unity
  Assets/AWSIM/Scripts/Loader/Loader.cs
  Assets/AWSIM/Scripts/Scene.meta
  Assets/AWSIM/Scripts/Scene/Editor.meta
  Assets/AWSIM/Scripts/Scene/Editor/SceneMetadataUpdater.cs
  Assets/AWSIM/Scripts/Scene/Editor/SceneMetadataUpdater.cs.meta
  Assets/AWSIM/Scripts/Scene/SceneMetadataDatabase.cs
  Assets/AWSIM/Scripts/Scene/SceneMetadataDatabase.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs
  Assets/ScenarioSimulatorConnector/Script/ScenarioSimulatorRequestProcessor.cs
  ProjectSettings/EditorBuildSettings.asset
  docs/Components/ScenarioSimulation/PreparingTheConnectionBetweenAWSIMAndScenarioSimulator/index.md
  docs/Components/ScenarioSimulation/SetupUnityProjectForScenarioSimulation/index.md
  docs/GettingStarted/UsingOpenSCENARIO/index.md
Labels: type:new-feature, tag:deploy-docs

#145 fix: vehicle initial gear
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs
Labels: type:bug

#148 fix: update vehicle hotkeys
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Resources/Hotkeys.json
  ProjectSettings/InputManager.asset
  docs/ProjectGuide/HotkeyList/index.md
Labels: tag:deploy-docs

#150 fix: add null checks when accessing camera components
  Assets/AWSIM/Scripts/UI/BirdEyeView.cs
  Assets/AWSIM/Scripts/UI/GraphicsSettings.cs
Labels: type:bug

#153 docs: remove pedal map step
  docs/GettingStarted/QuickStartDemo/index.md
Labels: type:documentation

#151 feat: vehicle dashboard
  Assets/AWSIM/Prefabs/UI/Vehicle Dashboard.prefab
  Assets/AWSIM/Prefabs/UI/Vehicle Dashboard.prefab.meta
  Assets/AWSIM/Prefabs/Vehicles/Lexus RX450h 2015 Sample Sensor.prefab
  Assets/AWSIM/Resources/Hotkeys.json
  Assets/AWSIM/Scenes/Composition/AWSIMSimulation.unity
  Assets/AWSIM/Scripts/Loader/SimConfiguration.cs
  Assets/AWSIM/Scripts/UI/Toggle/UIKeyboardControlToggle.cs
  Assets/AWSIM/Scripts/UI/VehicleDashboard.cs
  Assets/AWSIM/Scripts/UI/VehicleDashboard.cs.meta
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/IVehicleControlModes/ControlMode.cs
  Assets/AWSIM/Textures/UI Icons/auto_transmission_24dp_FFFFFF_FILL1_wght400_GRAD0_opsz20.png
  Assets/AWSIM/Textures/UI Icons/auto_transmission_24dp_FFFFFF_FILL1_wght400_GRAD0_opsz20.png.meta
  Assets/AWSIM/Textures/UI Icons/memory_40dp_FFFFFF_FILL1_wght400_GRAD0_opsz40.png
  Assets/AWSIM/Textures/UI Icons/memory_40dp_FFFFFF_FILL1_wght400_GRAD0_opsz40.png.meta
  Assets/AWSIM/Textures/UI Icons/person_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png
  Assets/AWSIM/Textures/UI Icons/person_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png.meta
  Assets/AWSIM/Textures/UI Icons/person_40dp_FFFFFF_FILL1_wght400_GRAD0_opsz40.png
  Assets/AWSIM/Textures/UI Icons/person_40dp_FFFFFF_FILL1_wght400_GRAD0_opsz40.png.meta
  docs/ProjectGuide/HotkeyList/index.md
Labels: type:new-feature

#156 fix: ego position update
  Assets/AWSIM/Scripts/UI/EgoVehiclePositionManager.cs
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs
Labels: type:bug

#158 fix: dummy message type
  Assets/AWSIM/Prefabs/Environments/Nishishinjuku/Nishishinjuku RandomTraffic.prefab
  Assets/AWSIM/Scenes/Main/AutowareSimulation.unity
  Assets/AWSIM/Scripts/NPCs/RvizNPCSpawner/RVIZNPCSpawner.cs
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_generator_c.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_generator_c.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_generator_py.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_generator_py.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_c.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_c.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_cpp.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_cpp.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_fastrtps_c.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_fastrtps_c.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_fastrtps_cpp.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_fastrtps_cpp.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_introspection_c.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_introspection_c.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_introspection_cpp.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs__rosidl_typesupport_introspection_cpp.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object__rosidl_typesupport_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object__rosidl_typesupport_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object__rosidl_typesupport_fastrtps_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object__rosidl_typesupport_fastrtps_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object__rosidl_typesupport_introspection_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object__rosidl_typesupport_introspection_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object_initial_state__rosidl_typesupport_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object_initial_state__rosidl_typesupport_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object_initial_state__rosidl_typesupport_fastrtps_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object_initial_state__rosidl_typesupport_fastrtps_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object_initial_state__rosidl_typesupport_introspection_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_dummy_object_initial_state__rosidl_typesupport_introspection_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_fault_injection_event__rosidl_typesupport_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_fault_injection_event__rosidl_typesupport_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_fault_injection_event__rosidl_typesupport_fastrtps_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_fault_injection_event__rosidl_typesupport_fastrtps_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_fault_injection_event__rosidl_typesupport_introspection_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_fault_injection_event__rosidl_typesupport_introspection_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_simulation_events__rosidl_typesupport_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_simulation_events__rosidl_typesupport_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_simulation_events__rosidl_typesupport_fastrtps_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_simulation_events__rosidl_typesupport_fastrtps_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_simulation_events__rosidl_typesupport_introspection_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_simulation_events__rosidl_typesupport_introspection_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value__rosidl_typesupport_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value__rosidl_typesupport_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value__rosidl_typesupport_fastrtps_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value__rosidl_typesupport_fastrtps_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value__rosidl_typesupport_introspection_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value__rosidl_typesupport_introspection_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value_type__rosidl_typesupport_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value_type__rosidl_typesupport_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value_type__rosidl_typesupport_fastrtps_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value_type__rosidl_typesupport_fastrtps_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value_type__rosidl_typesupport_introspection_c_native.so
  Assets/Ros2ForUnity/Plugins/Linux/x86_64/libtier4_simulation_msgs_user_defined_value_type__rosidl_typesupport_introspection_c_native.so.meta
  Assets/Ros2ForUnity/Plugins/tier4_simulation_msgs_assembly.deps.json
  Assets/Ros2ForUnity/Plugins/tier4_simulation_msgs_assembly.deps.json.meta
  Assets/Ros2ForUnity/Plugins/tier4_simulation_msgs_assembly.dll
  Assets/Ros2ForUnity/Plugins/tier4_simulation_msgs_assembly.dll.meta
Labels: type:bug

#164 fix: temp way to update default scene spawn points in the loader ui
  Assets/AWSIM/Scripts/Loader/EgosManager.cs
  Assets/AWSIM/Scripts/Loader/MapManager.cs
Labels: type:bug, type:enchantment

#159 docs: add info about wsl2 support
  docs/Introduction/AWSIM/index.md
Labels: type:documentation, tag:deploy-docs

#166 fix: reported velocity in reverse
  Assets/AWSIM/Scripts/Vehicles/VPP Integration/AutowareVPPAdapter.cs
Labels: type:bug

#168 docs: add recommended nvidia driver version
  docs/DeveloperGuide/TroubleShooting/index.md
  docs/GettingStarted/QuickStartDemo/index.md
Labels: type:documentation, tag:deploy-docs

#161 docs: fix missing parts related to parking area
  docs/GettingStarted/ParkingArea/index.md
  docs/GettingStarted/UsingOpenSCENARIO/index.md
Labels: type:documentation, tag:deploy-docs
